model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"

[features]
rmcp_client = true

[projects."/Users/travis/travis/homemgmt-ai"]
trust_level = "trusted"

[projects."/Users/travis/travis/homemgmt-ai-dragon"]
trust_level = "trusted"

[projects."/Users/travis/travis/homemgmt-ai-polar"]
trust_level = "trusted"

[projects."/Users/travis/git/polaris-naga-mono"]
trust_level = "trusted"

[projects."/Users/travis/git/polaris-naga-polar"]
trust_level = "trusted"

[projects."/Users/travis/.codex"]
trust_level = "trusted"

[projects."/Users/travis/git/polaris-naga-bubbles"]
trust_level = "trusted"

[projects."/Users/travis/travis/redcrayonwebsite"]
trust_level = "trusted"

[projects."/Users/travis/git/taos"]
trust_level = "trusted"

[projects."/Users/travis/travis/pdfs"]
trust_level = "trusted"

[projects."/Users/travis/git/polaris-cmp"]
trust_level = "trusted"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.figma]
type = "http"
url = "https://mcp.figma.com/mcp"

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest"]

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--context", "codex", "--enable-web-dashboard", "False"]
#
[notice]
hide_full_access_warning = true
hide_gpt5_1_migration_prompt = true
"hide_gpt-5.1-codex-max_migration_prompt" = true
# After codex has started, you need to activate the project, which you can do by saying:
# Activate the current dir as project using serena
